### ISSUE TITLE
Outdated master

### ISSUE THREAD

**Issue by vaiil** [Morning-Train/toggl-api#22]
Hello, I'm trying to contribute to your project, but I have met some problem. Your last version v2.0.0-alpha.3 is not merged to master. It's a bit confusing. I believe it would be better to make tags only from master branch.

**Comment by SimonJnsson** [comment]
Hey, for now the tag is alpha and not considered stable as we have only been able to set aside time for making specific changes, so the entire package is not yet considered up to date. If you are having issues using the master branch, feel free to simply require that specific tag in your project instead, but be aware that it may be unstable and/or subject to change.

**Comment by vaiil** [comment]
Hey @SimonJnsson, thanks for your reply. I just wanted to add `getPaginatedProjects` to TogglTrackMeApi, and I spent some time to understand which branch is alpha.3. Does it make sense to create develop (or v2) branch and make tags from it, if it is under development?

**Comment by SimonJnsson** [comment]
@vaiil you are free to make a PR with any changes that you need for your project. Currently we have no active development, but we do plan to update the package to an updated stable release at some point.
